import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {beforeEach,describe,it,expect,vi} from 'vitest';
import {LanguageProvider} from '@/context/LanguageContext';
import {LANGUAGE_STORAGE_KEY} from '@/lib/i18n';
import {projectSchema,getCompositionChoices,chooseComposition,generateCompositionChoices,type CompositionChoice} from '@/lib/project-api';
import fixture from '../../project-instructions/fixtures/demo-project.json';
import CompositionChooser from './CompositionChooser';
vi.mock('@/lib/project-api',async original=>({...await original<typeof import('@/lib/project-api')>(),getCompositionChoices:vi.fn(),chooseComposition:vi.fn(),generateCompositionChoices:vi.fn()}));
vi.mock('./DraftCanvas',()=>({default:({project,slideId}:{project:{slides:{id:string;scene?:{text:string;x:number}[]}[]};slideId:string})=><span data-testid="actual-preview">{project.slides.find(s=>s.id===slideId)?.scene?.map(e=>`${e.text}@${e.x}`).join(' / ')}</span>}));
function makeProject(){const p=projectSchema.parse(structuredClone(fixture));p.build_mode='model';p.slides=p.outline.map(item=>({id:item.id,status:'ready',revision:1,variants_status:'ready',variants_fingerprint:'current',selected_variant_id:'selected',blocks:{title:{text:item.title,status:'ready',revision:1},body:{text:item.key_message,status:'ready',revision:1},source_label:{text:'',status:'ready',revision:1}}}));return p;}
function makeChoices():CompositionChoice[]{return(['selected','alternative','out_of_box'] as const).map((id,i)=>({id,label:`Model option ${i+1}`,description:'Matches the accepted claim and notes',unconventional:id==='out_of_box',design:{layout:'editorial',emphasis:'quiet',rationale:'Accepted content',composition: i===2?'poster':'balanced',arrangement:'columns',focal_section_id:''},scene:[{kind:'text',x:7+i*20,y:9,w:30,h:12,text:'Actual accepted slide content',color:'#111111',size:3,bold:false,font:'Arial',block_key:'body',column:null}]}));}
beforeEach(()=>{vi.clearAllMocks();localStorage.setItem(LANGUAGE_STORAGE_KEY,'en');vi.mocked(getCompositionChoices).mockResolvedValue(makeChoices());});
const show=(p:ReturnType<typeof makeProject>,disabled=false,onChange=vi.fn())=><LanguageProvider><CompositionChooser project={p} slideId={p.slides[0].id} disabled={disabled} onChange={onChange}/></LanguageProvider>;
describe('Persisted AI variants',()=>{
 it('shows exactly three actual variants including the selected main slide',async()=>{const p=makeProject();render(show(p));await screen.findByRole('button',{name:'Choose Out of the box variant'});expect(screen.getAllByTestId('actual-preview').map(e=>e.textContent)).toEqual(['Actual accepted slide content@7','Actual accepted slide content@27','Actual accepted slide content@47']);expect(screen.getByRole('button',{name:'Choose Recommended variant'})).toHaveAttribute('aria-pressed','true');expect(screen.getByText('Selected · shown above')).toBeInTheDocument();expect(screen.getByText('Model option 3')).toBeInTheDocument();expect(generateCompositionChoices).not.toHaveBeenCalled();});
 it('does not invalidate final design when clicking the already selected card',async()=>{const p=makeProject();render(show(p));fireEvent.click(await screen.findByRole('button',{name:'Choose Recommended variant'}));expect(chooseComposition).not.toHaveBeenCalled();});
 it('reloads scene previews when the theme changes without regenerating plans',async()=>{const p=makeProject();const view=render(show(p));await screen.findByRole('button',{name:'Choose Recommended variant'});const fresh={...p,theme:'dark_tech_pitch' as const};view.rerender(show(fresh));await waitFor(()=>expect(getCompositionChoices).toHaveBeenCalledTimes(2));expect(generateCompositionChoices).not.toHaveBeenCalled();});
 it('selects a persisted alternative without generating a fourth option',async()=>{const p=makeProject(),fresh=structuredClone(p);fresh.slides[0].selected_variant_id='alternative';vi.mocked(chooseComposition).mockResolvedValue(fresh);const change=vi.fn();const view=render(show(p,false,change));fireEvent.click(await screen.findByRole('button',{name:'Choose Alternative variant'}));await waitFor(()=>expect(change).toHaveBeenCalledWith(fresh));expect(chooseComposition).toHaveBeenCalledWith(p,p.slides[0].id,'alternative');view.rerender(show(fresh,false,change));expect(screen.getByRole('button',{name:'Choose Alternative variant'})).toHaveAttribute('aria-pressed','true');expect(getCompositionChoices).toHaveBeenCalledTimes(1);expect(generateCompositionChoices).not.toHaveBeenCalled();});
 it('uses a truthful role label for the selected refined final design',async()=>{const p=makeProject();p.slides[0].selected_variant_id='alternative';p.slides[0].design_status='ready';p.slides[0].design={layout:'editorial',emphasis:'quiet',composition:'balanced',focal_section_id:'',rationale:'Final content arrangement',arrangement:'columns'};const choices=makeChoices();choices[1].label='Caution-first two-row layout';choices[1].description='Final approved content arranged in columns';vi.mocked(getCompositionChoices).mockResolvedValueOnce(choices);render(show(p));await screen.findByRole('button',{name:'Choose Alternative variant'});expect(screen.getByText('Alternative · final design')).toBeInTheDocument();expect(screen.queryByText('Caution-first two-row layout')).not.toBeInTheDocument();expect(screen.getByText('Final approved content arranged in columns')).toBeInTheDocument();expect(screen.getByText('Model option 1')).toBeInTheDocument();expect(screen.getByText('Model option 3')).toBeInTheDocument();});
 it('does not fetch stale previews and starts explicit generation for older slides',async()=>{const p=makeProject();p.slides[0].variants_status='none';const generating=structuredClone(p);generating.slides[0].variants_status='generating';vi.mocked(generateCompositionChoices).mockResolvedValue(generating);const change=vi.fn();const view=render(show(p,false,change));expect(getCompositionChoices).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Generate three variants with AI'}));await waitFor(()=>expect(change).toHaveBeenCalledWith(generating));expect(generateCompositionChoices).toHaveBeenCalledWith(p,p.slides[0].id);view.rerender(show(generating,false,change));expect(screen.getByRole('status')).toHaveTextContent('Creating three slide variants');expect(screen.queryAllByTestId('actual-preview')).toHaveLength(0);});
 it('keeps selection on failure and disables switching with unsaved content',async()=>{const p=makeProject(),change=vi.fn();const view=render(show(p,true,change));const button=await screen.findByRole('button',{name:'Choose Out of the box variant'});expect(button).toBeDisabled();view.rerender(show(p,false,change));vi.mocked(chooseComposition).mockRejectedValueOnce(new Error('Offline'));fireEvent.click(button);expect(await screen.findByRole('alert')).toHaveTextContent('Could not save this choice');expect(change).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Choose Recommended variant'})).toHaveAttribute('aria-pressed','true');});
 it('reloads unavailable persisted previews without issuing another model request',async()=>{vi.mocked(getCompositionChoices).mockRejectedValueOnce(new Error('Offline'));const p=makeProject();render(show(p));expect(await screen.findByRole('alert')).toHaveTextContent('Variants could not load');fireEvent.click(screen.getByRole('button',{name:'Reload variants'}));await screen.findByRole('button',{name:'Choose Out of the box variant'});expect(getCompositionChoices).toHaveBeenCalledTimes(2);expect(generateCompositionChoices).not.toHaveBeenCalled();});
});
