import {useState} from 'react';
import {render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import {beforeEach,describe,it,expect,vi} from 'vitest';
import LiveDraftEditor from './LiveDraftEditor';
import {LanguageProvider} from '@/context/LanguageContext';
import {LANGUAGE_STORAGE_KEY} from '@/lib/i18n';
import {projectSchema,getCompositionChoices,chooseComposition,downloadProjectPptx,type Project,type CompositionChoice} from '@/lib/project-api';
import fixture from '../../project-instructions/fixtures/demo-project.json';
vi.mock('@/lib/project-api',async original=>({...await original<typeof import('@/lib/project-api')>(),getCompositionChoices:vi.fn(),chooseComposition:vi.fn(),downloadProjectPptx:vi.fn()}));
vi.mock('./DraftCanvas',()=>({default:({project,slideId,onSelectBlock}:{project:Project;slideId:string;onSelectBlock?:unknown})=><div data-testid={onSelectBlock?'main-slide':'slide-preview'}>{project.slides.find(s=>s.id===slideId)?.scene?.map(e=>e.text).join(' / ')}</div>}));
const scene=(text:string):NonNullable<Project['slides'][number]['scene']>=>[{kind:'text',x:7,y:9,w:80,h:40,text,color:'#111111',size:3,bold:false,font:'Arial',block_key:'body',column:null}];
function makeProject(){const p=projectSchema.parse(structuredClone(fixture));p.phase='outline_draft';p.build_mode='model';p.slides=p.outline.map(item=>({id:item.id,status:'ready',revision:1,speaker_notes:'Spoken explanation corresponding to the visible argument.',variants_status:'ready',variants_fingerprint:'accepted-content',selected_variant_id:'selected',scene:scene('Selected slide arrangement'),blocks:{title:{text:item.title,status:'ready',revision:1},body:{text:item.key_message,status:'ready',revision:1},source_label:{text:'',status:'ready',revision:1}}}));return p;}
const choices:CompositionChoice[]=(['selected','alternative','out_of_box'] as const).map((id,i)=>({id,label:id,description:'Same approved content and notes',unconventional:i===2,design:{layout:'editorial',emphasis:'quiet',rationale:'Content priority',composition:'balanced',focal_section_id:''},scene:scene(i===0?'Selected slide arrangement':i===1?'Alternative slide arrangement':'Unexpected slide arrangement')}));
function Editor(){const [project,setProject]=useState(makeProject);return <LanguageProvider><LiveDraftEditor project={project} onChange={setProject}/></LanguageProvider>;}
beforeEach(()=>{vi.clearAllMocks();localStorage.setItem(LANGUAGE_STORAGE_KEY,'en');window.matchMedia=vi.fn().mockReturnValue({matches:false});vi.mocked(getCompositionChoices).mockResolvedValue(choices);});
describe('One selected slide among exactly three variants',()=>{
 it('main canvas is one of the three cards before and after selecting an alternative',async()=>{const p=makeProject(),fresh=structuredClone(p);fresh.slides[0].selected_variant_id='alternative';fresh.slides[0].scene=scene('Alternative slide arrangement');vi.mocked(chooseComposition).mockResolvedValue(fresh);render(<Editor/>);const options=await screen.findByRole('region',{name:'Slide composition options'});expect(within(options).getAllByRole('button')).toHaveLength(3);expect(screen.getByTestId('main-slide')).toHaveTextContent('Selected slide arrangement');expect(within(options).getByRole('button',{name:'Choose Recommended variant'})).toHaveTextContent('Selected slide arrangement');fireEvent.click(within(options).getByRole('button',{name:'Choose Alternative variant'}));await waitFor(()=>expect(screen.getByTestId('main-slide')).toHaveTextContent('Alternative slide arrangement'));expect(within(options).getAllByRole('button')).toHaveLength(3);expect(within(options).getByRole('button',{name:'Choose Alternative variant'})).toHaveAttribute('aria-pressed','true');});
 it.each(['drafting','designing'] as const)('shows arriving variants during %s without allowing edits',async(phase)=>{const p=makeProject();p.phase=phase;render(<LanguageProvider><LiveDraftEditor project={p} onChange={vi.fn()}/></LanguageProvider>);const button=await screen.findByRole('button',{name:'Choose Alternative variant'});expect(button).toBeDisabled();fireEvent.click(button);expect(chooseComposition).not.toHaveBeenCalled();expect(screen.getByTestId('main-slide')).toHaveTextContent('Selected slide arrangement');});
 it('places design retry controls in a separate scrolling region below the canvas',async()=>{const p=makeProject();p.slides[0].design_status='error';render(<LanguageProvider><LiveDraftEditor project={p} onChange={vi.fn()}/></LanguageProvider>);const retry=screen.getByRole('button',{name:'Update this slide’s design'});await screen.findByRole('button',{name:'Choose Recommended variant'});const controls=retry.closest('.draft-slide-controls');expect(controls).not.toBeNull();expect(controls).not.toContainElement(screen.getByTestId('main-slide'));expect(screen.getByTestId('main-slide').closest('.draft-slide-stage')?.nextElementSibling).toBe(controls);});
 it('blocks downloading a finished deck with unsaved speaker notes',async()=>{const p=makeProject();p.phase='ready';for(const slide of p.slides){slide.design_status='ready';slide.design=choices[0].design;}render(<LanguageProvider><LiveDraftEditor project={p} onChange={vi.fn()}/></LanguageProvider>);await screen.findByRole('button',{name:'Choose Recommended variant'});const download=screen.getByRole('button',{name:'Download PowerPoint'});expect(download).toBeEnabled();fireEvent.click(screen.getByRole('tab',{name:'Notes'}));fireEvent.click(screen.getByRole('button',{name:'Edit speaker notes'}));fireEvent.change(screen.getByRole('textbox',{name:'Speaker notes'}),{target:{value:'Unsaved spoken explanation'}});expect(download).toBeDisabled();expect(screen.getByText('Save or discard your edits before downloading PowerPoint.')).toBeInTheDocument();fireEvent.click(download);expect(downloadProjectPptx).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Discard note edits'}));expect(download).toBeEnabled();});
 it('preserves modified document navigation and supports plain tab navigation',async()=>{render(<Editor/>);await screen.findByRole('button',{name:'Choose Recommended variant'});const notes=screen.getByRole('tab',{name:'Notes'});fireEvent.click(notes);for(const modifiers of [{ctrlKey:true},{metaKey:true},{altKey:true},{shiftKey:true}]){fireEvent.keyDown(notes,{key:'Home',...modifiers});expect(notes).toHaveAttribute('aria-selected','true');}fireEvent.keyDown(notes,{key:'Home'});expect(screen.getByRole('tab',{name:'Content'})).toHaveAttribute('aria-selected','true');fireEvent.keyDown(screen.getByRole('tab',{name:'Content'}),{key:'ArrowRight'});expect(screen.getByRole('tab',{name:'Sources'})).toHaveAttribute('aria-selected','true');});
 it('reads notes beside the main slide and keeps unsaved notes across inspector tabs',async()=>{render(<Editor/>);await screen.findByRole('button',{name:'Choose Recommended variant'});fireEvent.click(screen.getByRole('tab',{name:'Notes'}));expect(screen.getByText('Spoken explanation corresponding to the visible argument.')).toBeVisible();expect(screen.getByTestId('main-slide')).toBeVisible();expect(screen.queryByRole('textbox',{name:'Speaker notes'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Edit speaker notes'}));fireEvent.change(screen.getByRole('textbox',{name:'Speaker notes'}),{target:{value:'Unsaved revised explanation'}});fireEvent.click(screen.getByRole('tab',{name:'Content'}));expect(screen.getByRole('button',{name:'Approve content & choose design'})).toBeDisabled();fireEvent.click(screen.getByRole('tab',{name:'Notes'}));expect(screen.getByRole('textbox',{name:'Speaker notes'})).toHaveValue('Unsaved revised explanation');expect(screen.getByTestId('main-slide')).toBeVisible();});
});
