import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {beforeEach,describe,it,expect,vi} from 'vitest';
import {LanguageProvider} from '@/context/LanguageContext';
import {LANGUAGE_STORAGE_KEY} from '@/lib/i18n';
import {projectSchema,saveSpeakerNotes} from '@/lib/project-api';
import fixture from '../../project-instructions/fixtures/demo-project.json';
import SpeakerNotesEditor from './SpeakerNotesEditor';
vi.mock('@/lib/project-api',async original=>({...await original<typeof import('@/lib/project-api')>(),saveSpeakerNotes:vi.fn()}));
function makeProject(){const p=projectSchema.parse(structuredClone(fixture));p.slides=p.outline.map((item,i)=>({id:item.id,status:'ready',revision:1,speaker_notes:`Saved notes ${i+1}`,blocks:{title:{text:item.title,status:'ready',revision:1},body:{text:item.key_message,status:'ready',revision:1},source_label:{text:'',status:'ready',revision:1}}}));return p;}
beforeEach(()=>{vi.clearAllMocks();localStorage.setItem(LANGUAGE_STORAGE_KEY,'en');});
function openNotes(){fireEvent.click(screen.getByRole('button',{name:'Edit speaker notes'}));}
describe('Speaker notes editing',()=>{
 it('saves notes independently and reports unsaved changes',async()=>{const p=makeProject(),fresh=structuredClone(p);fresh.slides[0].speaker_notes='Explain the claim and its evidence.';vi.mocked(saveSpeakerNotes).mockResolvedValue(fresh);const change=vi.fn(),dirty=vi.fn();const show=(project:typeof p)=><LanguageProvider><SpeakerNotesEditor project={project} slideId={p.slides[0].id} disabled={false} onChange={change} onDirtyChange={dirty}/></LanguageProvider>;const view=render(show(p));openNotes();expect(screen.getByRole('button',{name:'Save speaker notes'})).toBeDisabled();fireEvent.change(screen.getByRole('textbox',{name:'Speaker notes'}),{target:{value:fresh.slides[0].speaker_notes}});expect(dirty).toHaveBeenCalledWith(p.slides[0].id,'notes',true);fireEvent.click(screen.getByRole('button',{name:'Save speaker notes'}));await waitFor(()=>expect(change).toHaveBeenCalledWith(fresh));expect(saveSpeakerNotes).toHaveBeenCalledWith(p,p.slides[0].id,'Explain the claim and its evidence.');view.rerender(show(fresh));expect(screen.getByText(fresh.slides[0].speaker_notes!)).toBeInTheDocument();expect(screen.queryByRole('textbox')).not.toBeInTheDocument();expect(dirty).toHaveBeenLastCalledWith(p.slides[4].id,'notes',false);});
 it('retains drafts across slide switches and discards only the current slide draft',()=>{const p=makeProject(),dirty=vi.fn();const show=(slideId:string)=><LanguageProvider><SpeakerNotesEditor project={p} slideId={slideId} disabled={false} onChange={vi.fn()} onDirtyChange={dirty}/></LanguageProvider>;const view=render(show(p.slides[0].id));openNotes();fireEvent.change(screen.getByRole('textbox',{name:'Speaker notes'}),{target:{value:'Unsaved first-slide notes'}});view.rerender(show(p.slides[1].id));openNotes();expect(screen.getByRole('textbox',{name:'Speaker notes'})).toHaveValue('Saved notes 2');fireEvent.change(screen.getByRole('textbox',{name:'Speaker notes'}),{target:{value:'Unsaved second-slide notes'}});view.rerender(show(p.slides[0].id));expect(screen.getByRole('textbox',{name:'Speaker notes'})).toHaveValue('Unsaved first-slide notes');expect(dirty).toHaveBeenCalledWith(p.slides[1].id,'notes',true);fireEvent.click(screen.getByRole('button',{name:'Discard note edits'}));expect(screen.getByText('Saved notes 1')).toBeInTheDocument();view.rerender(show(p.slides[1].id));expect(screen.getByRole('textbox',{name:'Speaker notes'})).toHaveValue('Unsaved second-slide notes');});
 it('keeps edits after save failure and supports retry',async()=>{const p=makeProject(),change=vi.fn();vi.mocked(saveSpeakerNotes).mockRejectedValueOnce(new Error('Offline')).mockResolvedValueOnce(p);render(<LanguageProvider><SpeakerNotesEditor project={p} slideId={p.slides[0].id} disabled={false} onChange={change} onDirtyChange={vi.fn()}/></LanguageProvider>);openNotes();fireEvent.change(screen.getByRole('textbox',{name:'Speaker notes'}),{target:{value:'Keep these edits'}});fireEvent.click(screen.getByRole('button',{name:'Save speaker notes'}));expect(await screen.findByRole('alert')).toHaveTextContent('Your edits are kept');expect(screen.getByRole('textbox',{name:'Speaker notes'})).toHaveValue('Keep these edits');expect(change).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Save speaker notes'}));await waitFor(()=>expect(change).toHaveBeenCalledWith(p));expect(saveSpeakerNotes).toHaveBeenCalledTimes(2);});
 it('prevents edits while generation is active',()=>{const p=makeProject();render(<LanguageProvider><SpeakerNotesEditor project={p} slideId={p.slides[0].id} disabled={true} onChange={vi.fn()} onDirtyChange={vi.fn()}/></LanguageProvider>);expect(screen.getByText('Saved notes 1')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Edit speaker notes'})).toBeDisabled();});
});
